# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  

  pod 'SVProgressHUD'	
  pod 'ModelMapper'
  pod 'Moya/RxSwift'
  pod 'RxSwift',    '~> 3.0'
  pod 'RxCocoa',    '~> 3.0'
  pod 'Moya-ObjectMapper/RxSwift'
  pod 'SDWebImage'
  
  # Pods for Sample

  target 'SampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
